// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:plant_care_tracker/models/care_history.dart';
import 'package:plant_care_tracker/models/care_task.dart';
import 'package:plant_care_tracker/models/growth_entry.dart';
import 'package:plant_care_tracker/models/plant.dart';
import 'package:plant_care_tracker/models/room.dart';
import 'package:plant_care_tracker/models/watering_log.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CareHistoryAdapter());
    registerAdapter(CareTaskAdapter());
    registerAdapter(GrowthEntryAdapter());
    registerAdapter(PlantAdapter());
    registerAdapter(RoomAdapter());
    registerAdapter(WateringLogAdapter());
  }
}
